name: "Android Build"

on:
  workflow_call:
    inputs:
      environment:
        required: false
        type: string
        default: "release"
      publish:
        required: false
        type: boolean
        description: Publish to Appcenter
    secrets:
      APPCENTER_TOKEN_ANDROID:
        required: true
      ANDROID_KEYSTORE:
        required: true
      ANDROID_KEY_ALIAS:
        required: true
      ANDROID_KEYSTORE_PASSWORD:
        required: true

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: "yarn"

      - name: Install Node modules
        run: yarn ci

      - name: Cache Gradle Wrapper
        uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}

      - name: Cache Gradle Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-caches-

      - name: Make Gradlew Executable
        run: cd android && chmod +x ./gradlew
        # Build Command

      - name: Build Android ${{inputs.environment == 'release' && 'Release' || 'Debug'}}
        run: |
          cd android && ./gradlew bundle${{inputs.environment == 'release' && 'Release' || 'Debug'}} --no-daemon
      - run: pwd
      - name: Sign app APK
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: android/app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.ANDROID_KEYSTORE }}
          alias: ${{ secrets.ANDROID_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          # keyPassword: ${{ secrets.KEY_PASSWORD }}

      # Upload to Artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Timely.aab
          path: ${{steps.sign_app.outputs.signedReleaseFile}}

  publish-to-appcenter:
    if: ${{ inputs.publish == true }}
    runs-on: ubuntu-latest
    needs: build-android
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v3
        with:
          name: Timely.aab
          path: "android/"

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Upload artifact to App Center
        uses: wzieba/AppCenter-Github-Action@v1
        with:
          appName: paramsinghvc/Timely
          token: ${{secrets.APPCENTER_TOKEN_ANDROID}}
          group: UKInternal
          file: android/app-release.aab
          notifyTesters: true
          debug: false
