name: "iOS Build"

on:
  workflow_call:
    inputs:
      publish:
        required: false
        type: boolean
        description: Publish to Appcenter
    secrets:
      IOS_P12_BASE64:
        required: true
      IOS_MOBILEPROVISION_BASE64:
        required: true
      IOS_TEAM_ID:
        required: true
      IOS_CERTIFICATE_PASSWORD:
        required: true
      APPCENTER_TOKEN_IOS:
        required: true

jobs:
  build-ios:
    runs-on: macos-12 #Monterey
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: "yarn"

      - name: Install Node modules
        run: yarn ci
      - name: Restore Pods cache
        uses: actions/cache@v3
        with:
          path: |
            ios/Pods
            ~/Library/Caches/CocoaPods
            ~/.cocoapods
          key: ${{ runner.os }}-pods-${{ hashFiles('ios/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Install pod dependencies
        run: cd ios && pod install && cd ..

      - name: Build iOS (Release)
        uses: yukiarrr/ios-build-action@v1.5.0
        with:
          project-path: ios/Timely.xcodeproj
          p12-base64: ${{ secrets.IOS_P12_BASE64 }}
          mobileprovision-base64: ${{ secrets.IOS_MOBILEPROVISION_BASE64 }}
          code-signing-identity: "Apple Distribution"
          certificate-password: ${{ secrets.IOS_CERTIFICATE_PASSWORD }}
          team-id: ${{ secrets.IOS_TEAM_ID }}
          workspace-path: ios/Timely.xcworkspace
          output-path: "Timely.ipa"

      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: "Timely.ipa"
          path: "Timely.ipa"

  publish-to-appcenter:
    if: ${{ inputs.publish == true }}
    runs-on: ubuntu-latest
    needs: build-ios
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v3
        with:
          name: Timely.ipa
          path: "ios/"

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Upload artifact to App Center
        uses: wzieba/AppCenter-Github-Action@v1
        with:
          appName: paramsinghvc/Timely-iOS
          token: ${{secrets.APPCENTER_TOKEN_IOS}}
          group: UKInternal
          file: "ios/Timely.ipa"
          notifyTesters: true
          debug: false
